/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-16 18:48:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.carsales.model.Review;
import com.carsales.model.Car;
import java.util.*;
import java.text.NumberFormat;
import java.util.Locale;

public final class car_005freviews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1747400381863L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1747410052067L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.carsales.model.Car");
    _jspx_imports_classes.add("com.carsales.model.Review");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.text.NumberFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Car Reviews | Second-Hand Car Sales Platform</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .review-container {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-box {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-user {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .review-date {\r\n");
      out.write("            color: #888;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("        }\r\n");
      out.write("        .review-rating {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .star-filled {\r\n");
      out.write("            color: #FFD700;\r\n");
      out.write("        }\r\n");
      out.write("        .star-empty {\r\n");
      out.write("            color: #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .review-comment {\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("        .review-actions {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-summary {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("        .average-rating {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .average-rating .rating-value {\r\n");
      out.write("            font-size: 2em;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-count {\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("        .add-review-btn {\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .car-info-box {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            border-left: 4px solid #1e3c72;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("        }\r\n");
      out.write("        .car-info-box h3 {\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("            color: #1e3c72;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div style=\"display: flex; justify-content: space-between; align-items: center; padding: 0 20px;\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-car\"></i>\r\n");
      out.write("            Second-Hand Car Sales\r\n");
      out.write("        </h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\"><i class=\"fas fa-search\"></i> Browse Cars</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/reviews\"><i class=\"fas fa-star\"></i> Reviews</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/add\"><i class=\"fas fa-plus-circle\"></i> Sell a Car</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");

    // Get any session messages
    String message = (String) session.getAttribute("message");
    String messageType = (String) session.getAttribute("messageType");

    if (message != null) {
    
      out.write("\r\n");
      out.write("        <div class=\"alert alert-");
      out.print( messageType );
      out.write("\">\r\n");
      out.write("            ");
      out.print( message );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    ");

        // Clear the message after displaying it
        session.removeAttribute("message");
        session.removeAttribute("messageType");
    }

    List<Review> reviews = (List<Review>) request.getAttribute("reviews");
    Double averageRating = (Double) request.getAttribute("averageRating");
    Integer carId = (Integer) request.getAttribute("carId");
    Car car = (Car) request.getAttribute("car");
    NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(new Locale("en", "US"));
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("        <h2>Reviews for ");
      out.print( car != null ? car.getMake() + " " + car.getModel() + " (" + car.getYear() + ")" : "Car #" + carId );
      out.write("</h2>\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/view/");
      out.print( carId );
      out.write("\" class=\"btn btn-secondary\">\r\n");
      out.write("            <i class=\"fas fa-arrow-left\"></i> Back to Car Details\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (car != null) { 
      out.write("\r\n");
      out.write("    <div class=\"car-info-box\">\r\n");
      out.write("        <h3>");
      out.print( car.getMake() + " " + car.getModel() );
      out.write(' ');
      out.write('(');
      out.print( car.getYear() );
      out.write(")</h3>\r\n");
      out.write("        <p>ID: ");
      out.print( car.getId() );
      out.write(" | Price: ");
      out.print( currencyFormatter.format(car.getPrice()) );
      out.write("</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Review Summary -->\r\n");
      out.write("    <div class=\"review-summary\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"average-rating\">\r\n");
      out.write("                <div class=\"rating-value\">");
      out.print( String.format("%.1f", averageRating) );
      out.write("</div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    ");

                    int fullStars = (int) Math.floor(averageRating);
                    boolean hasHalfStar = averageRating - fullStars >= 0.5;

                    for (int i = 1; i <= 5; i++) {
                        if (i <= fullStars) {
                    
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-star star-filled\"></i>\r\n");
      out.write("                    ");
 } else if (i == fullStars + 1 && hasHalfStar) { 
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-star-half-alt star-filled\"></i>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <i class=\"far fa-star star-empty\"></i>\r\n");
      out.write("                    ");
 }
                    }
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"review-count\">");
      out.print( reviews.size() );
      out.write(" review");
      out.print( reviews.size() != 1 ? "s" : "" );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/reviews/add/");
      out.print( carId );
      out.write("\" class=\"btn btn-primary add-review-btn\">\r\n");
      out.write("            <i class=\"fas fa-plus\"></i> Write a Review\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Reviews List -->\r\n");
      out.write("    <div class=\"review-container\">\r\n");
      out.write("        ");
 if (reviews == null || reviews.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div style=\"text-align: center; padding: 40px 0;\">\r\n");
      out.write("                <p>No reviews yet. Be the first to review this car!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else {
            for (Review review : reviews) {
        
      out.write("\r\n");
      out.write("            <div class=\"review-box\">\r\n");
      out.write("                <div class=\"review-header\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"review-user\">");
      out.print( review.getUserName() );
      out.write("</div>\r\n");
      out.write("                        <div class=\"review-date\">");
      out.print( review.getFormattedDate() );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"review-actions\">\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/reviews/edit/");
      out.print( review.getId() );
      out.write("\" class=\"btn btn-secondary btn-sm\">\r\n");
      out.write("                            <i class=\"fas fa-edit\"></i> Edit\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/reviews/delete/");
      out.print( review.getId() );
      out.write("\"\r\n");
      out.write("                           onclick=\"return confirm('Are you sure you want to delete this review?')\"\r\n");
      out.write("                           class=\"btn btn-danger btn-sm\">\r\n");
      out.write("                            <i class=\"fas fa-trash\"></i> Delete\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-rating\">\r\n");
      out.write("                    ");
 for (int i = 1; i <= 5; i++) { 
      out.write("\r\n");
      out.write("                        <i class=\"");
      out.print( i <= review.getRating() ? "fas fa-star star-filled" : "far fa-star star-empty" );
      out.write("\"></i>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-comment\">\r\n");
      out.write("                    ");
      out.print( review.getComment() );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

            }
        }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div style=\"display: flex; flex-wrap: wrap; justify-content: space-between; padding: 0 20px; max-width: 1200px; margin: 0 auto;\">\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Second-Hand Car Sales</h3>\r\n");
      out.write("            <p>The trusted platform for buying and selling used vehicles.</p>\r\n");
      out.write("            <div style=\"margin-top: 15px;\">\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white;\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Quick Links</h3>\r\n");
      out.write("            <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/\" style=\"color: white; text-decoration: none;\">Home</a></li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\" style=\"color: white; text-decoration: none;\">Browse Cars</a></li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/add\" style=\"color: white; text-decoration: none;\">Sell a Car</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Contact Us</h3>\r\n");
      out.write("            <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-map-marker-alt\"></i> 123 Car Street, Autoville</li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-phone\"></i> +1 (555) 123-4567</li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-envelope\"></i> info@carsales.com</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"text-align: center; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.1);\">\r\n");
      out.write("        <p>© 2025 Second-Hand Car Sales Platform. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Add fade-out effect to alerts after 5 seconds\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const alerts = document.querySelectorAll('.alert');\r\n");
      out.write("        alerts.forEach(alert => {\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                alert.style.opacity = '0';\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    alert.style.display = 'none';\r\n");
      out.write("                }, 500);\r\n");
      out.write("            }, 5000);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
