/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-16 13:22:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.car;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1747400381863L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1747400364025L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Add New Car | Second-Hand Car Sales Platform</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div style=\"display: flex; justify-content: space-between; align-items: center; padding: 0 20px;\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-car\"></i>\r\n");
      out.write("            Second-Hand Car Sales\r\n");
      out.write("        </h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\"><i class=\"fas fa-search\"></i> Browse Cars</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/add\"><i class=\"fas fa-plus-circle\"></i> Sell a Car</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");

    // Get any session messages
    String message = (String) session.getAttribute("message");
    String messageType = (String) session.getAttribute("messageType");

    if (message != null) {
    
      out.write("\r\n");
      out.write("        <div class=\"alert alert-");
      out.print( messageType );
      out.write("\">\r\n");
      out.write("            ");
      out.print( message );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    ");

        // Clear the message after displaying it
        session.removeAttribute("message");
        session.removeAttribute("messageType");
    }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h2>Add New Car</h2>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print(request.getContextPath());
      out.write("/cars/add\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"make\">Make <span style=\"color: red\">*</span></label>\r\n");
      out.write("            <input type=\"text\" id=\"make\" name=\"make\" required placeholder=\"e.g., Toyota, Honda, Ford\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"model\">Model <span style=\"color: red\">*</span></label>\r\n");
      out.write("            <input type=\"text\" id=\"model\" name=\"model\" required placeholder=\"e.g., Corolla, Civic, Mustang\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"year\">Year <span style=\"color: red\">*</span></label>\r\n");
      out.write("            <input type=\"number\" id=\"year\" name=\"year\" required min=\"1900\" max=\"2025\" placeholder=\"e.g., 2018\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"price\">Price (USD) <span style=\"color: red\">*</span></label>\r\n");
      out.write("            <input type=\"number\" id=\"price\" step=\"0.01\" name=\"price\" required min=\"0\" placeholder=\"e.g., 15000\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"description\">Description</label>\r\n");
      out.write("            <textarea id=\"description\" name=\"description\" rows=\"5\" placeholder=\"Provide details about the vehicle condition, features, history, etc.\"></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"images\">Images</label>\r\n");
      out.write("            <div style=\"border: 2px dashed #ccc; padding: 20px; text-align: center; margin-bottom: 10px;\">\r\n");
      out.write("                <i class=\"fas fa-cloud-upload-alt\" style=\"font-size: 48px; color: #1e3c72; margin-bottom: 10px;\"></i>\r\n");
      out.write("                <p>Drag and drop images here or click to select files</p>\r\n");
      out.write("                <input type=\"file\" id=\"images\" name=\"images\" multiple accept=\"image/*\" style=\"display: none;\">\r\n");
      out.write("                <button type=\"button\" onclick=\"document.getElementById('images').click();\" class=\"btn btn-secondary\">\r\n");
      out.write("                    Select Files\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"image-preview\" style=\"display: flex; flex-wrap: wrap; gap: 10px;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; margin-top: 20px;\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\" class=\"btn btn-secondary\">\r\n");
      out.write("                <i class=\"fas fa-times\"></i> Cancel\r\n");
      out.write("            </a>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                <i class=\"fas fa-plus\"></i> Add Car\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div style=\"display: flex; flex-wrap: wrap; justify-content: space-between; padding: 0 20px; max-width: 1200px; margin: 0 auto;\">\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Second-Hand Car Sales</h3>\r\n");
      out.write("            <p>The trusted platform for buying and selling used vehicles.</p>\r\n");
      out.write("            <div style=\"margin-top: 15px;\">\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white;\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Quick Links</h3>\r\n");
      out.write("            <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/\" style=\"color: white; text-decoration: none;\">Home</a></li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\" style=\"color: white; text-decoration: none;\">Browse Cars</a></li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/add\" style=\"color: white; text-decoration: none;\">Sell a Car</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Contact Us</h3>\r\n");
      out.write("            <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-map-marker-alt\"></i> 123 Car Street, Autoville</li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-phone\"></i> +1 (555) 123-4567</li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-envelope\"></i> info@carsales.com</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"text-align: center; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.1);\">\r\n");
      out.write("        <p>© 2025 Second-Hand Car Sales Platform. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Image preview functionality\r\n");
      out.write("    document.getElementById('images').addEventListener('change', function() {\r\n");
      out.write("        const preview = document.getElementById('image-preview');\r\n");
      out.write("        preview.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("        if (this.files) {\r\n");
      out.write("            for (let i = 0; i < this.files.length; i++) {\r\n");
      out.write("                const file = this.files[i];\r\n");
      out.write("                if (!file.type.startsWith('image/')) continue;\r\n");
      out.write("\r\n");
      out.write("                const reader = new FileReader();\r\n");
      out.write("                reader.onload = function(e) {\r\n");
      out.write("                    const div = document.createElement('div');\r\n");
      out.write("                    div.style.width = '100px';\r\n");
      out.write("                    div.style.height = '100px';\r\n");
      out.write("                    div.style.overflow = 'hidden';\r\n");
      out.write("                    div.style.position = 'relative';\r\n");
      out.write("                    div.style.border = '1px solid #ddd';\r\n");
      out.write("                    div.style.borderRadius = '4px';\r\n");
      out.write("\r\n");
      out.write("                    const img = document.createElement('img');\r\n");
      out.write("                    img.src = e.target.result;\r\n");
      out.write("                    img.style.width = '100%';\r\n");
      out.write("                    img.style.height = '100%';\r\n");
      out.write("                    img.style.objectFit = 'cover';\r\n");
      out.write("\r\n");
      out.write("                    div.appendChild(img);\r\n");
      out.write("                    preview.appendChild(div);\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                reader.readAsDataURL(file);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Drag and drop functionality\r\n");
      out.write("    const dropZone = document.querySelector('div[style*=\"dashed\"]');\r\n");
      out.write("\r\n");
      out.write("    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\r\n");
      out.write("        dropZone.addEventListener(eventName, preventDefaults, false);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function preventDefaults(e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        e.stopPropagation();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ['dragenter', 'dragover'].forEach(eventName => {\r\n");
      out.write("        dropZone.addEventListener(eventName, highlight, false);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    ['dragleave', 'drop'].forEach(eventName => {\r\n");
      out.write("        dropZone.addEventListener(eventName, unhighlight, false);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function highlight() {\r\n");
      out.write("        dropZone.style.backgroundColor = '#f0f8ff';\r\n");
      out.write("        dropZone.style.borderColor = '#1e3c72';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function unhighlight() {\r\n");
      out.write("        dropZone.style.backgroundColor = '';\r\n");
      out.write("        dropZone.style.borderColor = '#ccc';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    dropZone.addEventListener('drop', handleDrop, false);\r\n");
      out.write("\r\n");
      out.write("    function handleDrop(e) {\r\n");
      out.write("        const dt = e.dataTransfer;\r\n");
      out.write("        const files = dt.files;\r\n");
      out.write("        const fileInput = document.getElementById('images');\r\n");
      out.write("\r\n");
      out.write("        fileInput.files = files;\r\n");
      out.write("\r\n");
      out.write("        // Trigger change event\r\n");
      out.write("        const event = new Event('change');\r\n");
      out.write("        fileInput.dispatchEvent(event);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
