/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-16 13:22:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.car;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.carsales.model.Car;
import java.util.*;
import java.text.NumberFormat;
import java.util.Locale;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1747400381863L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1747400364025L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.carsales.model.Car");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.text.NumberFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Car Details | Second-Hand Car Sales Platform</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div style=\"display: flex; justify-content: space-between; align-items: center; padding: 0 20px;\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-car\"></i>\r\n");
      out.write("            Second-Hand Car Sales\r\n");
      out.write("        </h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\"><i class=\"fas fa-search\"></i> Browse Cars</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/add\"><i class=\"fas fa-plus-circle\"></i> Sell a Car</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");
 Car car = (Car) request.getAttribute("car"); 
      out.write("\r\n");
      out.write("    ");
 NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(new Locale("en", "US")); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"car-detail\">\r\n");
      out.write("        <div class=\"car-detail-header\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h2 class=\"car-detail-title\">");
      out.print( car.getMake() + " " + car.getModel() );
      out.write(' ');
      out.write('(');
      out.print( car.getYear() );
      out.write(")</h2>\r\n");
      out.write("                <p>ID: ");
      out.print( car.getId() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"car-detail-price\">\r\n");
      out.write("                ");
      out.print( currencyFormatter.format(car.getPrice()) );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Car Gallery -->\r\n");
      out.write("        <div class=\"car-gallery\">\r\n");
      out.write("            ");
 if (car.getImages().length > 0) { 
      out.write("\r\n");
      out.write("                ");
 for (String image : car.getImages()) { 
      out.write("\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/cars/");
      out.print( image );
      out.write("\" alt=\"");
      out.print( car.getMake() + " " + car.getModel() );
      out.write("\">\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/cars/default-car.jpg\" alt=\"Default car image\">\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Car Specifications -->\r\n");
      out.write("        <div class=\"car-specs\">\r\n");
      out.write("            <div class=\"car-spec-item\">\r\n");
      out.write("                <div class=\"car-spec-label\">Make</div>\r\n");
      out.write("                <div class=\"car-spec-value\">");
      out.print( car.getMake() );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"car-spec-item\">\r\n");
      out.write("                <div class=\"car-spec-label\">Model</div>\r\n");
      out.write("                <div class=\"car-spec-value\">");
      out.print( car.getModel() );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"car-spec-item\">\r\n");
      out.write("                <div class=\"car-spec-label\">Year</div>\r\n");
      out.write("                <div class=\"car-spec-value\">");
      out.print( car.getYear() );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"car-spec-item\">\r\n");
      out.write("                <div class=\"car-spec-label\">Price</div>\r\n");
      out.write("                <div class=\"car-spec-value\">");
      out.print( currencyFormatter.format(car.getPrice()) );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Car Description -->\r\n");
      out.write("        <div class=\"car-description\">\r\n");
      out.write("            <h3>Description</h3>\r\n");
      out.write("            <p>");
      out.print( car.getDescription() != null && !car.getDescription().isEmpty() ? car.getDescription() : "No description available." );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Action Buttons -->\r\n");
      out.write("        <div style=\"display: flex; gap: 15px; margin-top: 20px;\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\" class=\"btn btn-secondary\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left\"></i> Back to Listings\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/edit/");
      out.print( car.getId() );
      out.write("\" class=\"btn btn-primary\">\r\n");
      out.write("                <i class=\"fas fa-edit\"></i> Edit\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/delete/");
      out.print( car.getId() );
      out.write("\"\r\n");
      out.write("               onclick=\"return confirm('Are you sure you want to delete this car?')\"\r\n");
      out.write("               class=\"btn btn-danger\">\r\n");
      out.write("                <i class=\"fas fa-trash\"></i> Delete\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Similar Cars Section -->\r\n");
      out.write("    ");
 List<Car> similarCars = (List<Car>) request.getAttribute("similarCars"); 
      out.write("\r\n");
      out.write("    ");
 if (similarCars != null && !similarCars.isEmpty()) { 
      out.write("\r\n");
      out.write("        <div style=\"margin-top: 40px;\">\r\n");
      out.write("            <h3>Similar Cars You Might Like</h3>\r\n");
      out.write("            <div class=\"car-grid\">\r\n");
      out.write("                ");
 for (Car similarCar : similarCars) {
                    String imageSrc = similarCar.getImages().length > 0
                        ? request.getContextPath() + "/images/cars/" + similarCar.getImages()[0]
                        : request.getContextPath() + "/images/cars/default-car.jpg";
                
      out.write("\r\n");
      out.write("                    <div class=\"car-card\" onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/cars/view/");
      out.print( similarCar.getId() );
      out.write("'\">\r\n");
      out.write("                        <div class=\"car-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( imageSrc );
      out.write("\" alt=\"");
      out.print( similarCar.getMake() + " " + similarCar.getModel() );
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"car-info\">\r\n");
      out.write("                            <h3 class=\"car-title\">");
      out.print( similarCar.getMake() + " " + similarCar.getModel() );
      out.write("</h3>\r\n");
      out.write("                            <p class=\"car-details\">");
      out.print( similarCar.getYear() );
      out.write("</p>\r\n");
      out.write("                            <p class=\"car-price\">");
      out.print( currencyFormatter.format(similarCar.getPrice()) );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div style=\"display: flex; flex-wrap: wrap; justify-content: space-between; padding: 0 20px; max-width: 1200px; margin: 0 auto;\">\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Second-Hand Car Sales</h3>\r\n");
      out.write("            <p>The trusted platform for buying and selling used vehicles.</p>\r\n");
      out.write("            <div style=\"margin-top: 15px;\">\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white; margin-right: 15px;\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\" style=\"color: white;\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Quick Links</h3>\r\n");
      out.write("            <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/\" style=\"color: white; text-decoration: none;\">Home</a></li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/cars\" style=\"color: white; text-decoration: none;\">Browse Cars</a></li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/cars/add\" style=\"color: white; text-decoration: none;\">Sell a Car</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; min-width: 200px; margin: 10px;\">\r\n");
      out.write("            <h3>Contact Us</h3>\r\n");
      out.write("            <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-map-marker-alt\"></i> 123 Car Street, Autoville</li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-phone\"></i> +1 (555) 123-4567</li>\r\n");
      out.write("                <li style=\"margin-bottom: 5px;\"><i class=\"fas fa-envelope\"></i> info@carsales.com</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"text-align: center; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.1);\">\r\n");
      out.write("        <p>© 2025 Second-Hand Car Sales Platform. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
